In [6]:
import tensorflow as tf
t = tf.constant([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
]) # a matrix 
t

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [13]:
t1  = t[..., 1, tf.newaxis]
display(t1)
t2 = t[:,:,1,tf.newaxis]
display(t2)
t_ = t[0]
t_

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]])>

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]])>

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [18]:
t_ @ tf.transpose(t_)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])>