In [1]:
import numpy as np

In [167]:
# Creating random matrices to truly test the versatility of our code
def createrandomfloatmatrix(m_shape,n_shape):
    import random as rd
    matrix = np.zeros((m_shape, n_shape))
    for m in range(m_shape):
        for n in range(n_shape):
            matrix[m,n] = rd.randrange(1,10)
        
    return matrix

def triangular(A,b):
    for m in range(np.shape(A)[0]):
        # print(m) 0,1,2
        f = A[m,m]
        A[m,:] =  A[m,:] / f
        b[0,m] =  b[0,m] / f

        for i in range(np.shape(A)[0]-1-m):
            A[i+1+m,:] = A[i+1+m,:] - A[m,:]*A[i+1+m,m]
            b[0,i+1+m] = b[0,i+1+m] - b[0,m]*A[i+1+m,m]
    return A,b

# backsub !?




def solveAxb(A,b):
    # starting from row m(max)-1, subract this row * value of target row from all other rows
    # ... repeat until target row indices iterated
    # ... repeat until "killer" row is row index 1
    A,b = triangular(A,b)

    for tm in range(np.shape(A)[0]-1):
        i = np.shape(A)[0] - tm - 1
        for m in range(np.shape(A)[0]-1-tm):
            A[m,:] = A[m,:] - A[i,:]*A[m,i]
            b[0,m] = b[0,m] - b[0,i]*A[m,i]
    return A,b

mA = createrandomfloatmatrix(5,5)
vb = createrandomfloatmatrix(1,5)
print("Matrix Org")
print(mA)
print("Vector Org")
print(vb)

rmA, rvb = solveAxb(mA,vb)

print("Result Matrix: ")
print(np.round(rmA))
print("Result Vector: ")
print(np.round(np.transpose(rvb)))


Matrix Org
[[7. 5. 9. 8. 9.]
 [6. 9. 1. 9. 6.]
 [3. 6. 8. 4. 6.]
 [4. 4. 1. 7. 9.]
 [6. 9. 6. 1. 5.]]
Vector Org
[[3. 8. 5. 9. 7.]]
Result Matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Result Vector: 
[[0.]
 [2.]
 [1.]
 [6.]
 [0.]]


In [89]:
# Testing Function

A_test = np.array([[1., 1, 1],[1,  2, 3],[1,  2, 4]])
b_test = np.array([6.,14,17])

A_,b_ = triangular(mA,vb)
rmA, rvb = solveAxb(A_,b_)

print("Result Matrix: ")
print(np.round(rmA))
print("Result Vector: ")
print(np.round(np.transpose(rvb)))

Result Matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Result Vector: 
[[ 1.]
 [14.]
 [-0.]
 [ 0.]
 [ 2.]]


In [110]:
smX = np.matrix([[3,3],
                 [4,3]])

def detAij(tbt_M):
    return tbt_M[0,0]*tbt_M[1,1] - tbt_M[0,1]*tbt_M[1,0]

detAij(smX)

-3

In [170]:
tmA = createrandomfloatmatrix(4,4)
tmB = createrandomfloatmatrix(4,4)

def Inverse(A):
    # Part 1 (Triangular)
    b = np.eye(np.shape(A)[0])

    #   triangular
    for m in range(np.shape(A)[0]):
        # print(m) 0,1,2
        f = A[m,m]
        A[m,:] =  A[m,:] / f
        b[m,:] =  b[m,:] / f

        for i in range(np.shape(A)[0]-1-m):
            A[i+1+m,:] = A[i+1+m,:] - A[m,:]*A[i+1+m,m]
            b[i+1+m,:] = b[i+1+m,:] - b[m,:]*A[i+1+m,m]

        print(f"Checkpoint (Triangle {m})")
        print(np.round(A))
        print(b)
    
    #   solve
    for tm in range(np.shape(A)[0]-1):
        i = np.shape(A)[0] - tm - 1
        for m in range(np.shape(A)[0]-1-tm):
            A[m,:] = A[m,:] - A[i,:]*A[m,i]
            b[m,:] = b[m,:] - b[i,:]*A[m,i]

    print("")
    print("A, b after")
    print(np.round(A))
    print(np.round(b))
    return b



Inverse(tmA)

Checkpoint (Triangle 0)
[[1. 1. 0. 1.]
 [9. 9. 5. 9.]
 [7. 7. 7. 1.]
 [1. 2. 5. 2.]]
[[0.14285714 0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]]
Checkpoint (Triangle 1)
[[ 1.  1.  0.  1.]
 [-0.  1. -0. -0.]
 [ 0. -2.  4. -5.]
 [ 0.  1.  5.  1.]]
[[ 0.14285714  0.          0.          0.        ]
 [-0.         -0.38888889 -0.         -0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Checkpoint (Triangle 2)
[[ 1.  1.  0.  1.]
 [-0.  1. -0. -0.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  5.  2.]]
[[ 0.14285714  0.          0.          0.        ]
 [-0.         -0.38888889 -0.         -0.        ]
 [ 0.          0.          0.32142857  0.        ]
 [ 0.          0.          0.          1.        ]]
Checkpoint (Triangle 3)
[[ 1.  1.  0.  1.]
 [-0.  1. -0. -0.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  1.]]
[[ 0.14285714

array([[ 0.14285714,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.38888889, -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.32142857,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.09150327]])

In [ ]:
# testing inverse with hand calculated example

test_A = np.matrix([[1.,0.,1.],[0.,2.,1.],[1.,1.,1.]])

In [171]:
Eye = np.eye(3)
print(Eye)

Eye[0,2] = 4
print(Eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 4.]
 [0. 1. 0.]
 [0. 0. 1.]]
